### ISSUE TITLE
Connection refused error

### ISSUE THREAD

**Issue by MarAlder** [megasanjay/electron-vue3-flask#27]
**Describe the bug**
I'm building the app, install via `vue-electron-flask Setup 1.0.1.exe` and run the app. Everything is fine. Then I copy `vue-electron-flask Setup 1.0.1.exe` to a different computer with the same setup (also running Windows 10). After installing and running the app I get a `net::ERROR_CONNECTION_REFUSED`: 

![grafik](https://user-images.githubusercontent.com/43143741/210600240-e7360853-ddcd-4655-a9bb-29103d88dc4a.png)

Any idea what happens here?

**Comment by Szhiha** [comment]
I followed the tutorial under wsl2+Ubuntu 20.04, but in the end, the starting log/n Trace/breakpoint trap was displayed

**Comment by megasanjay** [comment]
@Szhiha I would try not using wsl2 for Electron. either go native Linux or windows.

**Comment by MarAlder** [comment]
Is this related to my question?
